version: '3.8'

services:
  nexusai-forge:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER:-flows_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-flows_password}
      - POSTGRES_DB=${POSTGRES_DB:-flows_db}
      - POSTGRES_HOST=db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      - SECRET_KEY=${SECRET_KEY}
      - SECURE_COOKIES=${SECURE_COOKIES:-true}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-100}
      - RATE_LIMIT_TIMEFRAME=${RATE_LIMIT_TIMEFRAME:-60}
      - MAX_AUTH_FAILURES=${MAX_AUTH_FAILURES:-5}
      - AUTH_LOCKOUT_MINUTES=${AUTH_LOCKOUT_MINUTES:-15}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-changeme}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - SECURITY_LOG_PATH=${SECURITY_LOG_PATH:-logs/security.log}
    volumes:
      - .:/app
      - ./logs:/app/logs
      - nexusai_data:/app/data
    depends_on:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - nexusai_network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-flows_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-flows_password}
      - POSTGRES_DB=${POSTGRES_DB:-flows_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - nexusai_network

volumes:
  postgres_data:
  nexusai_data:

networks:
  nexusai_network:
    driver: bridge
