
services:
  nexusai-forge:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://flows_user:flows_password@db:5432/flows_db
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
      - nexusai_data:/app/data
    depends_on:
      - db
    networks:
      - nexusai_network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=flows_user
      - POSTGRES_PASSWORD=flows_password
      - POSTGRES_DB=flows_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - nexusai_network
    restart: unless-stopped

volumes:
  postgres_data:
  nexusai_data:

networks:
  nexusai_network:
    driver: bridge
